// Account Actions
export const SEARCH_ACCOUNTS_REQUEST = 'SEARCH_ACCOUNTS_REQUEST';
export const SEARCH_ACCOUNTS_ERRORED = 'SEARCH_ACCOUNTS_ERRORED';
export const SEARCH_ACCOUNTS_LOADING = 'SEARCH_ACCOUNTS_LOADING';
export const SEARCH_ACCOUNTS_SUCCESS = 'SEARCH_ACCOUNTS_SUCCESS';
export const ACCOUNT_SELECTED = 'ACCOUNT_SELECTED';
export const INPUT_CHANGE = 'INPUT_CHANGE';

// Account Details Actions
export const FETCH_ACCOUNT_DETAILS_LOADING = 'FETCH_ACCOUNT_DETAILS_LOADING';
export const FETCH_ACCOUNT_DETAILS_ERRORED = 'FETCH_ACCOUNT_DETAILS_ERRORED';
export const FETCH_ACCOUNT_DETAILS_SUCCESS = 'FETCH_ACCOUNT_DETAILS_SUCCESS';

// Narrative Chart Actions
export const SET_MOUSE_LOCATION = 'SET_MOUSE_LOCATION';
export const SET_TRENDLINE_METRICS = 'SET_TRENDLINE_METRICS';

